### ISSUE TITLE
性能问题

### ISSUE THREAD

**Issue by shiluoma** [Chaunjie/weapp-scroll-view-refresh#1]
经测试，真机上使用时，如果拖动比较快、距离比较大，动画会有抖动（在没有放手进入touend事件的情况下），延长delay也无效

**Comment by Chaunjie** [comment]
ios上面的确会出现距离比较大的问题，还在查找原因，请问你用什么机子测试会出现抖动的问题，我这边测试了红米5A还好@shiluoma

**Comment by shiluoma** [comment]
使用的iphone6和小米4，iphone6比较明显，小米4还好。本来怀疑是iphone自己的回弹导致，可是在不放手的情况下，测试过其它页面是不会回弹的。个人感觉还是比较像js线程卡住延迟执行了，另外页面滑动后的点击事件也会受影响，明显反应比静态下慢不少。
可能我需要在scroll事件中也做限流，可是没想到合适的兼顾scroll\touch同步的方案，后来我把动画效果关闭了，直接展示加载数据的loading图片。
谢谢你的分享和回复~~

**Comment by Chaunjie** [comment]
你说的回弹是指的拉的过大然后回弹到一定位置然后显示loading状态吗，另外页面滑动后点击事件有延迟是scroll-view本身的问题，今天修复了ios下面下拉拖动比较快、距离比较大的问题，同时也优化了动画频繁调用的问题，明天会上一个版本，谢谢你的意见

**Comment by shiluoma** [comment]
不是的，我的操作过程是这样的:快速下拉页面，拉动比较大的幅度，然后手指停住（不要放开，这时不会到touchEnd事件中，也就不会出现loading状态），这时候页面顶部会先缩回去一段距离，然后再返回到我拉动停留的位置。
至于放手出现loading这个过程，目前没发现任何问题。

**Comment by Chaunjie** [comment]
好的，我针对这个去看看，是ios下面会出现这样的问题吗

**Comment by shiluoma** [comment]
是的
